spring.application.name=market-service
server.port=8082

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

spring.data.mongodb.uri=mongodb://mongodb:27017/marketdb

spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.player-service.sliding-window-size=5
resilience4j.circuitbreaker.instances.player-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.player-service.wait-duration-in-open-state=10s

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://tempo:4317
management.opentelemetry.tracing.export.otlp.transport=grpc

logging.pattern.level=%5p [%X{correlationId}] [traceId=%X{traceId} spanId=%X{spanId}]