spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=player-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://player-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/players/**

spring.cloud.gateway.server.webflux.routes[1].id=market-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://market-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/items/**,/api/listing/**

management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://tempo:4317
management.opentelemetry.tracing.export.otlp.transport=grpc